# Generated by Django 4.1.5 on 2023-05-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'VERIFIED'), (0, 'INITIAL'), (1, 'UNVERIFIED')], default=0, null=True),
        ),
    ]
