# Generated by Django 4.2.1 on 2023-05-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'INITIAL'), (2, 'VERIFIED'), (1, 'UNVERIFIED')], default=0, null=True),
        ),
    ]
