# Generated by Django 4.2.1 on 2023-05-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'UNVERIFIED'), (2, 'VERIFIED'), (0, 'INITIAL')], default=0, null=True),
        ),
    ]
