# Generated by Django 4.2.1 on 2023-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_status_alter_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'staff'), (1, 'admin')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'UNVERIFIED'), (0, 'INITIAL'), (2, 'VERIFIED')], default=0, null=True),
        ),
    ]
