# Generated by Django 4.1.5 on 2023-05-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'UNVERIFIED'), (2, 'VERIFIED'), (0, 'INITIAL')], default=0, null=True),
        ),
    ]
