# Generated by Django 4.1.5 on 2023-05-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_record_brand_of_vaccine_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='place_of_vaccine',
            field=models.SmallIntegerField(choices=[(1, 'Tai Wai'), (0, 'Sha Tin')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='brand_of_vaccine',
            field=models.SmallIntegerField(choices=[(1, 'CoronaVac'), (0, 'Comirnaty')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'Other'), (1, 'F'), (0, 'M')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ACTIVE'), (3, 'DELETED'), (0, 'INITIAL'), (2, 'INACTIVE')], default=1, null=True),
        ),
    ]
