# Generated by Django 4.2.1 on 2023-05-24 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname_en', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname_en', models.CharField(blank=True, max_length=200, null=True)),
                ('firstname_zh', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(2, 'Other'), (0, 'M'), (1, 'F')], default=2, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_of_vaccine', models.SmallIntegerField(blank=True, choices=[(1, 'CoronaVac'), (0, 'Comirnaty')], default=0, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'INITIAL'), (2, 'INACTIVE'), (3, 'DELETED'), (1, 'ACTIVE')], default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
