# Generated by Django 4.2.1 on 2023-05-24 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('ref_code', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False)),
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname_en', models.CharField(max_length=200, null=True)),
                ('lastname_en', models.CharField(max_length=200, null=True)),
                ('firstname_zh', models.CharField(max_length=200, null=True)),
                ('lastname_zh', models.CharField(max_length=200, null=True)),
                ('id_number', models.CharField(max_length=200, null=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'M'), (2, 'Other'), (1, 'F')], default=2, null=True)),
                ('date_of_birth', models.DateField()),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('place_of_birth', models.CharField(max_length=200, null=True)),
                ('brand_of_vaccine', models.SmallIntegerField(choices=[(1, 'CoronaVac'), (0, 'Comirnaty')], default=0, null=True)),
                ('verify_identity', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(3, 'DELETED'), (2, 'INACTIVE'), (1, 'ACTIVE'), (0, 'INITIAL')], default=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
