# Generated by Django 4.2.1 on 2023-05-24 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'F'), (0, 'M'), (2, 'Other')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ref_code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'INACTIVE'), (3, 'DELETED'), (1, 'ACTIVE'), (0, 'INITIAL')], default=1, null=True),
        ),
    ]
