# Generated by Django 4.2.1 on 2023-05-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ref_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'Other'), (0, 'M'), (1, 'F')], default=2, null=True),
        ),
    ]
