# Generated by Django 4.2.1 on 2023-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_record_gender_alter_record_ref_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'M'), (2, 'Other'), (1, 'F')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (0, 'INITIAL'), (3, 'DELETED')], default=1, null=True),
        ),
    ]
